#!/usr/bin/env bash
#script to configure domain zone
get_record_info() {
  local domain="$1"
  local subdomain="$2"
  
  if [[ -z "$subdomain" ]]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi
  
  for sub in "${subdomains[@]}"; do
    record_type=$(dig +short "$sub.$domain" | awk 'NR==1{print $4}')
    destination=$(dig +short "$sub.$domain" | awk 'NR==1{print $5}')
    echo "The subdomain $sub is a $record_type record and points to $destination"
  done
}

get_record_info "$1" "$2"
