#!/usr/bin/env bash
#some script
frontend http_frontend
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }

frontend https_frontend
    bind *:443 ssl crt /etc/letsencrypt/live/www.genyarko.tech/fullchain.pem
    mode http
    option httplog
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    option http-server-close
    option forwardfor
    server web-01 100.24.206.17:80 check
    server web-02 54.173.234.218:80 check
