#!/usr/bin/env bash

# Update the system packages
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

# Configure Nginx to use the custom 404 page
cat <<EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}
EOF

# Restart Nginx
service nginx restart
