#!/usr/bin/env bash
# This script configures Nginx to include a custom HTTP response header.

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Add custom header configuration to Nginx
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom_header.conf

# Restart Nginx
sudo service nginx restart
