#!/usr/bin/env bash
# This script creates a PID file and displays messages for various signals.

# Create the PID file
echo $$ > /var/run/myscript.pid

# Trap signals and display messages
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Display messages indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 2
done
