#!/usr/bin/env bash
# This script creates a PID file and displays messages for various signals.


terminator() {
  rm /var/run/myscript.pid
  exit
}

# Trap signals and display messages
trap 'echo "Y U no love me?!" && terminator' SIGINT
trap 'echo "I hate the kill command" && terminator' SIGTERM
trap 'terminator' SIGQUIT

# Create the PID file
echo "$$" > /var/run/myscript.pid

# Display messages indefinitely
while true
do
  echo "To infinity and beyond"
  sleep 2
done
