#!/usr/bin/env bash
# create PID file
echo $$ > /var/run/myscript.pid

# trap signals
trap 'echo "I hate the kill command"; exit 1' SIGTERM
trap 'echo "Y U no love me?!"; exit 1' SIGINT
trap 'rm /var/run/myscript.pid; exit 0' SIGQUIT SIGTERM

# infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done

