#!/usr/bin/env bash
# This script displays lines containing the "bash" word.
# shellcheck disable=SC2009
# Disable Shellcheck warning SC2009 (regarding the use of `ps -ef | grep`)
# since it is being used intentionally in this script.


# Use the ps command to display all running processes, with full format,
# and grep for lines containing the "bash" word.
ps -ef | grep bash
