#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely.

# Use a while loop to display the message indefinitely.
while true; do
    echo "To infinity and beyond"
    sleep 2
done
