#!/usr/bin/env bash
# This script displays "To infinity and beyond indefinitely" and sleeps for 2 seconds between iterations.
# It displays "I am invincible!!!" when receiving a SIGTERM signal.
# This version stops the 7-highlander process instead of the 4-to_infinity_and_beyond one.

while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
