#!/usr/bin/env bash
# This script kills the process 7-highlander.

# Use the ps command to find the PID of the process.
# Check if the process is still running and terminate it if it is.

pkill -f -SIGKILL 7-highlander

