#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
minute=1

while [ $hour -lt 13 ]
do
  printf "%02d:%02d\n" $hour $minute

  if [ $minute -eq 59 ]
  then
    hour=$((hour+1))
    minute=0
  else
    minute=$((minute+1))
  fi
done | head -n 70
