#!/usr/bin/env bash
# This script displays the content of the current directory
# in a list format, where only the part of the name after
# the first dash is displayed

for file in *
do
  if [ "${file:0:1}" != "." ] && [ -f "$file" ]
  then
    file_name="$(echo "$file" | cut -d'-' -f2-)"
    printf "%s\n" "$file_name"
  fi
done
